- name: Benchmark speedup_customAllocator
  vars:
    bench_name: speedup_customAllocator
    data_dir: "{{ json_data_folder }}/{{ bench_name }}"
    elements: "{{ 2**30 }}"
    data_type: "double"
    data_type_filter: "/{{ data_type }}/{{ elements }}"
    threads: "{{ ansible_processor_nproc }}"
  block:
    - name: Set bench allocators based on build allocators
      ansible.builtin.set_fact:
        backends: >-
          {{
            backends | combine({
              item.key: item.value | combine({
                'bench': item.value.bench | combine({
                  'default_allocator': true,
                  'custom_allocator': item.value.build.custom_allocator
                })
              })
            })
          }}
      loop: "{{ backends | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
      tags:
        - speedup_customAllocator
        - speedup_customAllocator_moveFiles
        - debug_speedup_customAllocator

    - name: Remove the backends that do not have both bench default_allocator and custom_allocator
      ansible.builtin.set_fact:
        backends: >-
          {{
            backends
            | dict2items
            | selectattr('value.bench.default_allocator', 'equalto', true)
            | selectattr('value.bench.custom_allocator', 'equalto', true)
            | list
            | items2dict
          }}
      loop: "{{ backends | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
      when: not item.value.bench.default_allocator or not item.value.bench.custom_allocator
      tags:
        - speedup_customAllocator
        - speedup_customAllocator_moveFiles
        - debug_speedup_customAllocator

    - name: Set again fact for selected cmake builds
      ansible.builtin.set_fact:
        cmake_benchs: "{{ selected_algorithms | product(backends | dict2items) | list | selectattr('1.key', 'in', selected_backends) | list }}"
      tags:
        - speedup_customAllocator
        - speedup_customAllocator_moveFiles
        - debug_speedup_customAllocator

    - name: Run speedup_customAllocator
      ansible.builtin.include_tasks: "benchmark.yml"
      tags:
        - speedup_customAllocator

    # use --tags=debug_speedup_customAllocator when running the playbook to see the debug output
    - name: Print speedup_customAllocator commands
      ansible.builtin.include_tasks: "debug/debug_benchmark.yml"
      tags:
        - never
        - debug_speedup_customAllocator

    - name: Ensure custom_allocator and default_allocator directories exist
      ansible.builtin.file:
        path: "{{ data_dir }}/{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - da
        - ca
      tags:
        - speedup_customAllocator
        - speedup_customAllocator_moveFiles

    - name: Set fact product of allocators and selected algorithms
      ansible.builtin.set_fact:
        allocators_algorithms: "{{ ['da', 'ca'] | product(selected_algorithms) | list }}"
      tags:
        - speedup_customAllocator
        - speedup_customAllocator_moveFiles
        - debug_speedup_customAllocator

    - name: Ensure the algorithm directories exist for each allocator
      ansible.builtin.file:
        path: "{{ data_dir }}/{{ item.0 }}/{{ item.1 }}{{ '-k' + (kit | string) if item.1 == 'for_each' else '' }}"
        state: directory
        mode: "0755"
      loop: "{{ allocators_algorithms }}"
      loop_control:
        label: "{{ item.0 }}-{{ item.1 }}"
      tags:
        - speedup_customAllocator
        - speedup_customAllocator_moveFiles

    - name: Move files to correct directories
      ansible.builtin.shell: >
        mv
        {{ data_dir }}/{{ item.1 }}{{ '-k' + (kit | string) if item.1 == 'for_each' else '' }}/*-{{ item.0 }}*.json
        {{ data_dir }}/{{ item.0 }}/{{ item.1 }}{{ '-k' + (kit | string) if item.1 == 'for_each' else '' }}
      loop: "{{ allocators_algorithms }}"
      loop_control:
        label: "{{ item.0 }}-{{ item.1 }}"
      register: move_result
      failed_when: move_result.rc != 0
      changed_when: move_result.rc == 0
      tags:
        - speedup_customAllocator
        - speedup_customAllocator_moveFiles

    - name: Deleted old algorithms directories
      ansible.builtin.file:
        path: "{{ data_dir }}/{{ item }}{{ '-k' + (kit | string) if item == 'for_each' else '' }}"
        state: absent
      loop: "{{ selected_algorithms }}"
      tags:
        - speedup_customAllocator
        - speedup_customAllocator_moveFiles

    - name: Print move files commands
      ansible.builtin.debug:
        msg: >-
          mv {{ data_dir }}/{{ item.1 }}{{ '-k' + (kit | string) if item.1 == 'for_each' else '' }}/*-{{ item.0 }}*.json
          {{ data_dir }}/{{ item.0 }}/{{ item.1 }}{{ '-k' + (kit | string) if item.1 == 'for_each' else '' }}
      loop: "{{ allocators_algorithms }}"
      loop_control:
        label: "{{ item.0 }}-{{ item.1 }}"
      tags:
        - never
        - debug_speedup_customAllocator
