- name: Print CMake create command
  tags:
    - never
    - debug
  block:
    - name: Create default allocator double
      ansible.builtin.debug:
        msg: >
          {{ item.value.pre_cmd }}
          cmake {{ cmake.release }}
          {{ cmake.backend }}={{ item.value.build.backend }}
          {{ cmake.compiler }}={{ item.value.build.compiler }}
          {{ cmake.data_type }}=double
          {{ cmake.compiler_flags }}='{{ item.value.build.compiler_flags }}'
          {{ item.value.build.cmake_flags }}
          -S . -B {{ builds_dir }}/{{ item.key }}-da-double
      loop: "{{ cmake_builds }}"
      loop_control:
        label: "{{ item.key }}"
      when: item.key in selected_backends
      tags:
        - default_allocator
        - double

    - name: Create custom allocator double
      ansible.builtin.debug:
        msg: >
          {{ item.value.pre_cmd }}
          cmake {{ cmake.release }}
          {{ cmake.backend }}={{ item.value.build.backend }}
          {{ cmake.compiler }}={{ item.value.build.compiler }}
          {{ cmake.data_type }}=double
          {{ cmake.compiler_flags }}='{{ item.value.build.compiler_flags }}'
          {{ item.value.build.cmake_flags }}
          -S . -B {{ builds_dir }}/{{ item.key }}-ca-double
      loop: "{{ cmake_builds }}"
      loop_control:
        label: "{{ item.key }}"
      when: item.key in selected_backends and item.value.build.custom_allocator
      tags:
        - custom_allocator
        - double

    - name: Create default allocator float
      ansible.builtin.debug:
        msg: >
          {{ item.value.pre_cmd }}
          cmake {{ cmake.release }}
          {{ cmake.backend }}={{ item.value.build.backend }}
          {{ cmake.compiler }}={{ item.value.build.compiler }}
          {{ cmake.data_type }}=float
          {{ cmake.compiler_flags }}='{{ item.value.build.compiler_flags }}'
          {{ item.value.build.cmake_flags }}
          -S . -B {{ builds_dir }}/{{ item.key }}-da-float
      loop: "{{ cmake_builds }}"
      loop_control:
        label: "{{ item.key }}"
      when: item.key in selected_backends and item.value.build.build_float
      tags:
        - default_allocator
        - float

    - name: Create custom allocator float
      ansible.builtin.debug:
        msg: >
          {{ item.value.pre_cmd }}
          cmake {{ cmake.release }}
          {{ cmake.backend }}={{ item.value.build.backend }}
          {{ cmake.compiler }}={{ item.value.build.compiler }}
          {{ cmake.custom_allocator_on }}
          {{ cmake.data_type }}=float
          {{ cmake.compiler_flags }}='{{ item.value.build.compiler_flags }}'
          {{ item.value.build.cmake_flags }}
          -S . -B {{ builds_dir }}/{{ item.key }}-ca-float
      loop: "{{ cmake_builds }}"
      loop_control:
        label: "{{ item.key }}"
      when: item.key in selected_backends and item.value.build.build_float and item.value.build.custom_allocator
      tags:
        - custom_allocator
        - float
