- name: Build CMake benchmarks
  hosts: all

  vars:
    env: "test"
    skip_backends: []

  become: false
  gather_facts: true
  any_errors_fatal: false

  pre_tasks:
    - name: Load global variables from file
      ansible.builtin.include_vars: "../global_vars.yml"
      tags:
        - always

    - name: Load local variables from file
      ansible.builtin.include_vars: "vars.yml"
      tags:
        - always

    - name: Skipping the build for the following backends
      ansible.builtin.debug:
        msg: "{{ skip_backends }}"
      when: skip_backends | length > 0
      tags:
        - always

    - name: Set fact for available cmake builds
      ansible.builtin.set_fact:
        cmake_builds: "{{ kits | product(backends | dict2items) | list }}"
      tags:
        - always

    - name: Set the root directory to dev
      ansible.builtin.set_fact:
        root: "{{ ansible_env.HOME }}/{{ project_name }}.dev"
      when: env == 'dev'
      tags:
        - always

    - name: Print the root directory
      ansible.builtin.debug:
        msg: "Root directory: {{ root }}"
      tags:
        - always

    - name: Ensure the git repository is cloned
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: "{{ root }}"
        version: "main"
        force: true
      tags:
        - create_cmakes
        - build_cmakes

    - name: Ensure the builds directory exists
      ansible.builtin.file:
        path: "{{ builds_dir }}"
        state: directory
        mode: "0755"
      tags:
        - create_cmakes
        - build_cmakes

    - name: Apt update
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400 # 1 day
      tags:
        - create_cmakes
        - build_cmakes

    - name: Install dependencies
      become: true
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - build-essential
        - cmake
        - libboost-all-dev
        - numactl
        - libnuma-dev
        - parallel
        - librust-tcmalloc-dev
        - hwloc
      tags:
        - create_cmakes
        - build_cmakes

  tasks:
    - name: Create CMakes
      ansible.builtin.include_tasks: "tasks/cmake_create.yml"
      tags:
        - create_cmakes

    - name: Build CMakes
      ansible.builtin.include_tasks: "tasks/cmake_build.yml"
      tags:
        - build_cmakes

    # use --tags=debug when running the playbook to see the debug output
    - name: Print create CMakes commands
      ansible.builtin.include_tasks: "tasks/debug/debug_cmake_create.yml"
      tags:
        - never
        - debug

      # use --tags=debug when running the playbook to see the debug output
    - name: Print build CMakes commands
      ansible.builtin.include_tasks: "tasks/debug/debug_cmake_build.yml"
      tags:
        - never
        - debug
