- name: Build CMake benchmarks
  hosts: all

  become: false
  gather_facts: true
  any_errors_fatal: false

  pre_tasks:
    - name: Load global variables from file
      ansible.builtin.include_vars: "../global_vars.yml"
      tags:
        - always

    - name: Load local variables from file
      ansible.builtin.include_vars: "vars.yml"
      tags:
        - always

    - name: Ensure the git repository is cloned
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: "{{ root }}"
        version: "main"
        force: true

    - name: Ensure the builds directory exists
      ansible.builtin.file:
        path: "{{ builds_dir }}"
        state: directory
        mode: '0755'

    - name: "Apt update"
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400 # 1 day

    - name: "Install dependencies"
      become: true
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - build-essential
        - cmake
        - libboost-all-dev
        - numactl
        - libnuma-dev
        - parallel
        - librust-tcmalloc-dev
        - hwloc

  tasks:
    - name: Create CMakes
      ansible.builtin.include_tasks: "tasks/cmake.yml"
      loop: "{{ kits | product(backends | dict2items) | list }}"
      loop_control:
        label: "{{ item.1.key }}-k{{item.0}}"

    - name: Debug the CMake debug commands
      ansible.builtin.include_tasks: "tasks/debug_cmake.yml"
      loop: "{{ kits | product(backends | dict2items) | list }}"
      loop_control:
        label: "{{ item.1.key }}-k{{item.0}}"
      tags:
        - never
        - debug
