- name: Build CMakes
  tags:
    - build_cmakes
  ignore_errors: true
  any_errors_fatal: false
  block:
    - name: Build default allocator double
      ansible.builtin.shell:
        cmd: >
          {{ item.value.pre_cmd }}
          cmake --build {{ builds_dir }}/{{ item.key }}-da-double
          --target {{ project_name }}
        chdir: "{{ root }}"
      loop: "{{ cmake_builds }}"
      loop_control:
        label: "{{ item.key }}"
      register: _res
      changed_when: _res.rc == 0
      when: item.key in selected_backends
      tags:
        - default_allocator
        - double

    - name: Build custom allocator double
      ansible.builtin.shell:
        cmd: >
          {{ item.value.pre_cmd }}
          cmake --build {{ builds_dir }}/{{ item.key }}-ca-double
          --target {{ project_name }}
        chdir: "{{ root }}"
      loop: "{{ cmake_builds }}"
      loop_control:
        label: "{{ item.key }}"
      register: _res
      changed_when: _res.rc == 0
      when: item.key in selected_backends and item.value.build.custom_allocator
      tags:
        - custom_allocator
        - double

    - name: Build default allocator float
      ansible.builtin.shell:
        cmd: >
          {{ item.value.pre_cmd }}
          cmake --build {{ builds_dir }}/{{ item.key }}-da-float
          --target {{ project_name }}
        chdir: "{{ root }}"
      loop: "{{ cmake_builds }}"
      loop_control:
        label: "{{ item.key }}"
      register: _res
      changed_when: _res.rc == 0
      when: item.key in selected_backends and item.value.build.build_float
      tags:
        - default_allocator
        - float

    - name: Build custom allocator float
      ansible.builtin.shell:
        cmd: >
          {{ item.value.pre_cmd }}
          cmake --build {{ builds_dir }}/{{ item.key }}-ca-float
          --target {{ project_name }}
        chdir: "{{ root }}"
      loop: "{{ cmake_builds }}"
      loop_control:
        label: "{{ item.key }}"
      register: _res
      changed_when: _res.rc == 0
      when: item.key in selected_backends and item.value.build.build_float and item.value.build.custom_allocator
      tags:
        - custom_allocator
        - float
