- name: Create CMakes
  tags:
    - create_cmakes
  block:
    - name: "{{ item.1.key }}-k{{ item.0 }} default allocator double"
      ansible.builtin.command:
        cmd: >
          cmake {{ cmake.release }}
          {{ cmake.backend }}={{ item.1.value.build.backend }}
          {{ cmake.compiler }}={{ item.1.value.build.compiler }}
          {{ cmake.kit }}={{ item.0 }}
          {{ cmake.data_type }}=double
          {{ item.1.value.build.compiler_flags }}
          -S . -B {{ builds_dir }}/{{ item.1.key }}-k{{ item.0 }}-da-double
        chdir: "{{ root }}"
      register: gnu_build
      changed_when: gnu_build.rc == 0
      tags:
        - default_allocator
        - double

    - name: "{{ item.1.key }}-k{{ item.0 }} custom allocator double"
      ansible.builtin.command:
        cmd: >
          cmake {{ cmake.release }}
          {{ cmake.backend }}={{ item.1.value.build.backend }}
          {{ cmake.compiler }}={{ item.1.value.build.compiler }}
          {{ cmake.custom_allocator_on }}
          {{ cmake.kit }}={{ item.0 }}
          {{ cmake.data_type }}=double
          {{ item.1.value.build.compiler_flags }}
          -S . -B {{ builds_dir }}/{{ item.1.key }}-k{{ item.0 }}-ca-double
        chdir: "{{ root }}"
      register: gnu_build
      changed_when: gnu_build.rc == 0
      when: item.1.value.build.custom_allocator
      tags:
        - custom_allocator
        - double

    - name: "{{ item.1.key }}-k{{ item.0 }} default allocator float"
      ansible.builtin.command:
        cmd: >
          cmake {{ cmake.release }}
          {{ cmake.backend }}={{ item.1.value.build.backend }}
          {{ cmake.compiler }}={{ item.1.value.build.compiler }}
          {{ cmake.kit }}={{ item.0 }}
          {{ cmake.data_type }}=float
          {{ item.1.value.build.compiler_flags }}
          -S . -B {{ builds_dir }}/{{ item.1.key }}-k{{ item.0 }}-da-float
        chdir: "{{ root }}"
      register: gnu_build
      changed_when: gnu_build.rc == 0
      when: item.1.value.build.build_float
      tags:
        - default_allocator
        - float

    - name: "{{ item.1.key }}-k{{ item.0 }} custom allocator float"
      ansible.builtin.command:
        cmd: >
          cmake {{ cmake.release }}
          {{ cmake.backend }}={{ item.1.value.build.backend }}
          {{ cmake.compiler }}={{ item.1.value.build.compiler }}
          {{ cmake.custom_allocator_on }}
          {{ cmake.kit }}={{ item.0 }}
          {{ cmake.data_type }}=float
          {{ item.1.value.build.compiler_flags }}
          -S . -B {{ builds_dir }}/{{ item.1.key }}-k{{ item.0 }}-ca-float
        chdir: "{{ root }}"
      register: gnu_build
      changed_when: gnu_build.rc == 0
      when: item.1.value.build.build_float and item.1.value.build.custom_allocator
      tags:
        - custom_allocator
        - float
