name: CI/CD Pipeline

on:
  push: { } # Run this workflow on push events (all branches)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run apt update
        run: sudo apt update

      - name: Set up CMake
        run: |
          sudo apt install -y cmake
          cmake --version
          echo "cmake version: $(cmake --version)"

      - name: Set up C++ compiler (11 or newer)
        run: |
          sudo apt install -y g++-11
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 90
          c++ --version
          echo "c++ version: $(c++ --version)"

      - name: Set up libnuma
        run: |
          sudo apt install -y libnuma-dev
          echo "libnuma version: $(dpkg -s libnuma-dev | grep Version)"

      - name: Set up libPFM
        run: |
          sudo apt install -y libpfm4-dev
          echo "libpfm version: $(dpkg -s libpfm4-dev | grep Version)"

      - name: Set up Google Benchmark
        run: |
          sudo apt install -y libbenchmark-dev
          echo "benchmark version: $(dpkg -s libbenchmark-dev | grep Version)"

      - name: Set up TBB
        run: |
          sudo apt install -y libtbb2-dev
          echo "tbb version: $(dpkg -s libtbb-dev | grep Version)"


      - name: Build application with CMake (no options)
        run: |
          mkdir build
          cd build
          PSTL_BUILD_OPTIONS="-DCMAKE_BUILD_TYPE=Release -DPSTL_BENCH_BACKEND=TBB -DPSTL_BENCH_USE_PAR_ALLOC=ON"
          cmake .. ${PSTL_BUILD_OPTIONS}
          make
          echo "Application built successfully! (${PSTL_BUILD_OPTIONS})"

      - name: Build application with CMake (enable GNU parallel STL)
        run: |
          mkdir build-gpstl
          cd build-gpstl
          PSTL_BUILD_OPTIONS="-DCMAKE_BUILD_TYPE=Release -DPSTL_BENCH_BACKEND=GNU -DPSTL_BENCH_USE_PAR_ALLOC=ON"
          cmake .. ${PSTL_BUILD_OPTIONS}
          make
          echo "Application built successfully! (${PSTL_BUILD_OPTIONS})"
